### ISSUE TITLE
gpujpeg_decoder_decode hanging.

### ISSUE THREAD

**Issue by wolfviking0** [CESNET/GPUJPEG#52]
Hi @MartinPulec ,

I am facing another new issue, it could be more tricky to reproduce because its happen with a specific configuration. I am using swig to generate an interface in python for GPUJPEG.

One of my function do a decoding from a numpy array (JPEG data) to a torch tensor. 

```
bool JPGUtil::loadFromMemory(int64_t tensorptr, const uint32_t csize, uint8_t* ptr)
{
    if (_decoder == nullptr) {
        Log::error("JPGUtil::load(): invalid decoder.\n");
        return false;
    }

    Log::warning("AL --> loadFromMemory()\n");
    
    gpujpeg_set_device(_gpu_id);

    gpujpeg_decoder_set_output_format(_decoder, _param_image.color_space, _param_image.pixel_format);

    // set decoder default output destination
    struct gpujpeg_decoder_output decoder_output;
    gpujpeg_decoder_output_set_custom_cuda(&decoder_output, (uint8_t*)tensorptr);

    Log::warning("AL --> loadFromMemory() decode %d\n", csize);
    
    if (gpujpeg_decoder_decode(_decoder, ptr, csize, &decoder_output) != 0) {
        return false;
    }

    Log::warning("AL --> loadFromMemory() finish\n");
    
    return true;
}
 ```

Some time (not all the time) it seems the gpujpeg_decoder_decode block and hang I see my GPU process going crazy and my code just stuck here.
Do you have any idea why I could have the decode function going into some kind of infinite loop ?

**Comment by wolfviking0** [comment]
I spend my day on it and I was not able to figure out but I found a workaround:
1 - use gpujpeg_decoder_output_set_default instead of gpujpeg_decoder_output_set_custom_cuda
2 - do a cuda memcpy
```
    struct gpujpeg_decoder_output decoder_output;
    //gpujpeg_decoder_output_set_custom_cuda(&decoder_output, (uint8_t*)tensorptr);
    gpujpeg_decoder_output_set_default(&decoder_output);
    
    Log::warning("decoding %d...\n",csize);
    if (gpujpeg_decoder_decode(_decoder, ptr, csize, &decoder_output) != 0) {
        return false;
    }
    Log::warning("... decoding ...\n");
    cudaMemcpy((uint8_t*)tensorptr, decoder_output.data, decoder_output.data_size, cudaMemcpyDeviceToDevice);
    Log::warning("... decoding\n");
```

**Comment by MartinPulec** [comment]
Hard to say... What about killing the process with a signal that causes core dump generation (eg. SIGQUIT) and generating a core dump? There may be visible at least a location of the problem.

Generally speaking I think it may be deployment-specific, but I cannot generally reproduce.

Another thing worth trying may be to use GPUJPEG in a separate CUDA stream to see if the problem persists.

**Comment by wolfviking0** [comment]
So I try various stuff but same killing do not give info, the only thing I know for sure is the hang is related to the call of cudaStreamSynchronize, thats not helping much :(

https://github.com/CESNET/GPUJPEG/blob/a715baba4029ce7ae74a7becccf0197462e3af69/src/gpujpeg_decoder.c#L329

```
    // Wait for async operations before copying from the device
    cudaStreamSynchronize(decoder->stream);
```

**Comment by MartinPulec** [comment]
Thanks a lot for debugging the problem. Is there any specific image that triggers the issue (if so, I'd ask you for it)?

I've not written that code, but the `coefficient_value` should be correctly incremented at least by a value 1 every `gpujpeg_huffman_gpu_decoder_get_coefficient` call (so that loop definitely should end), the appropriate value should be originally set here:

https://github.com/CESNET/GPUJPEG/blob/a715baba4029ce7ae74a7becccf0197462e3af69/src/gpujpeg_huffman_gpu_decoder.cu#L560

I am thinking that it may wrong value taken from quick table here:

https://github.com/CESNET/GPUJPEG/blob/a715baba4029ce7ae74a7becccf0197462e3af69/src/gpujpeg_huffman_gpu_decoder.cu#L289-L292

I don't know how easily you can reproduce the issue (I unfortunately currently cannot), but could you try to replace the above by taking the values from the "full" table directly by following:
```
unsigned int packed_info = gpujpeg_huffman_gpu_decoder_tables_full[table_idx];
```

But it is currently just a shot in the dark, not sure if it helps. But if so, it would reduce the problem space nicely.

Anyways, thanks a lot!

**Comment by wolfviking0** [comment]
Hi @MartinPulec, I apply the change you suggest me and unfortunately the hanging its still happening.

Maybe one extra piece of information, the code who hang is running into another thread. I don't know if that can have a consequences

**Comment by wolfviking0** [comment]
Assuming the problem is related to the table, is there anything I can print in order to help to have more information for debugging ?

**Comment by MartinPulec** [comment]
> Maybe one extra piece of information, the code who hang is running into another thread. I don't know if that can have a consequences

Can I ask for more info about that? The function `gpujpeg_huffman_gpu_decoder_decode` is one block so I assume that `gpujpeg_decoder_init` is called from one thread and decoder_decode() from another?

> Assuming the problem is related to the table, is there anything I can print in order to help to have more information for debugging ?

Not really, it looks like there is not correct values, but the question is why - would it be possible to provide the code (or ideally a minimal working example)? The thing is that it is that it would be useful to see the conditions which trigger that behavior, which I currently don't see.

**Comment by wolfviking0** [comment]
Hi @MartinPulec based on your previous comment I tried to each time I want to uncompress the texture in my thread to recreate the decoder calling both gpujpeg_decoder_init and gpujpeg_huffman_gpu_decoder_decode so everything leave in the same thread, unfortunately still happening.

I will try to create a sample, but it will took some time because I really have a reproduction case only when using the python wrapping so far so that imply a lot of code.

**Comment by MartinPulec** [comment]
Hi @wolfviking0, I understand that. Basically it doesn't need to be a minimal working example. If it is possible to create any working example it may help. It depends how much work it requires - basically I could make some probes which I'll ask you to examine, but currently I don't have such a hot tip (as I thought the tables had been).

**Comment by wolfviking0** [comment]
Hi @MartinPulec I tried to reduce my sample but its really difficult.

One thing so, I can see the issue is related to multithreading. I tried to just create GPUJPEG into another thread and I start to have some weird images sometime.

It could be some trouble related to missing mutex maybe ... or missing synchronize I am not sure yet. If I move the Huffman decoder on CPU the trouble is gone on Mac no more hanging and on Linux no more artifact.

I will try to find more stuff to provide to you.

**Comment by MartinPulec** [comment]
> One thing so, I can see the issue is related to multithreading. I tried to just create GPUJPEG into another thread and I start to have some weird images sometime.

I see, then there can be problems with global static variables. What is actually the mode of operation in your use case?

1. using multiple threads single GPU, but only decoding at most one image at the same time
2. -------------------" ----------------------, possibly concurrent decoding on single GPU
3. multiple GPUs, multiple CPU threads, but decoding on single GPU at the same time (roughly analogous to # 1) 
4.  ----------------- " ------------------------- with possibility of concurrent decoding on single GPU

Not sure if the points above are clear enough but basically the points 2 and 4 are problematic - i. e. when decoding concurrently on one GPU from multiple host threads. Can this be the case?

Init from one thread and decode from the other should not AFAIK be a problem (but we can look at it if so).

Regards,
Martin

**Comment by MartinPulec** [comment]
I've created a branch [wip-disable-quick-tables](https://github.com/CESNET/GPUJPEG/tree/wip-disable-quick-tables) which disables quick Huffman GPU tables by default (can be enabled with `--enable-huffman-gpu-quick-tables` with autoconf or `-DHUFFMAN_GPU_QUICK_TABLES=ON` for CMake). If my suspicion is correct, it may fix the problem (not sure how reproducible it is for you, anyway).

Moreover it looks like the Huffman code runs even slightly faster without looking into the quick tables.

**Comment by wolfviking0** [comment]
Hi @MartinPulec 
In my case  2 and 4 are my use case. I am currently testing the branch and one of my code was failing each time so it was easy to reproduce, but on your branch it seems to be working fine.

I will update my code to use this branch for the next few days so I can be 100% sure this branch fix the issue, I will keep you updated. 

THanks

**Comment by wolfviking0** [comment]
Hi @MartinPulec, so for the past 2 days I generate various video for testing your branch, so far everything seems to be working smoothly on both OSX and LINUX using multithread and multigpus.

**Comment by MartinPulec** [comment]
Hi Anthony, good thanks - that makes perfectly sense, I'll push the fixes then. Actually I don't think that there is an advantage of use constant CUDA memory (for which static/global variable is needed), at least for the Huffman decoder (it is faster than L2 cache only if accessing the same element from all threads, which is not the case).

**Comment by wolfviking0** [comment]
@MartinPulec I just spot maybe another issue related to this branch

Some texture are coming corrupted on OSX, initially I was thinking it was a bug in my blending function, but linux is ok.
After disabling again Huffman from GPU there is no more issue. The thing is the artefact look really different of the previous one.

And again before doing the blending I am doing some decoding. Also using another thread.
I try on GPU0 or GPU1 but the issue still happen. One thing, it seems that happen when my thread go slower. If I use smaller resolution its not happening.

[example.zip](https://github.com/CESNET/GPUJPEG/files/5674919/example.zip)

**Comment by MartinPulec** [comment]
Thanks @wolfviking0, I've just pushed my current updates - if you'd be able if it is also there it would be perfect. Anyways, just for my info - the decoding to texture you mean to OpenGL texture or CUDA buffer (gpujpeg_decoder_output_set_XY)? I am not sure if it is related, because the Huffman decoding comes first, so I'd suspect that it occurs also when decoding to CPU buffer then. But there may be different timing to blame, so yep, it may be related. And indeed, the image looks like there is a problem with the Huffman decoder, indeed.

I think, however, that the problematic parts we've discovered should be eliminated by the fixes. I'll also try to replicate that as well, it is also possible that I've missed something in the fix that exhibits only on mac.

**Comment by wolfviking0** [comment]
Hi @MartinPulec,

I am using cuda buffer, I just pull your latest code on your branch but I still the same artifact when running one of the thread.

**Comment by MartinPulec** [comment]
> I am using cuda buffer, I just pull your latest code on your branch but I still the same artifact when running one of the thread.

Just to be sure - I meant the master branch, in wip-disable-quick-tables there is no further changes (and I've deleted it from server). In master, there is further one table moved from const memory to device. There should not be any static vars left in the GPU decoder now.

**Comment by MartinPulec** [comment]
I've created a very simple testing app [decode_to_cuda_pnm.c](https://github.com/CESNET/GPUJPEG/blob/master/examples/decode_to_cuda_pnm.c). But as expected, it didn't exhibit the problem with JPEG generated from [sample image](https://github.com/CESNET/GPUJPEG/blob/master/colors/camera_bt709_422.yuv) in the repo. Unfortunately in this case, I currently don't have clear opinion where the problem can be. Any further info would by highly appreciated.

**Comment by wolfviking0** [comment]
Hi @MartinPulec, I was testing your latest master branch all day, all my video was working without any issues, no artefact.
Thanks you.

**Comment by MartinPulec** [comment]
Hi, good - that is also an important information for me - I didn't expect that moving the order tables in const memory would make a difference - there may be a race, but the copied tables are still the same and it is done only in decoder init. In that case I'd remove all that remaining variables then (IIRC this is further left in the Huffman GPU encoder only).
